# Generated by Django 5.1.6 on 2026-04-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechaPublicacion', models.DateField(auto_now_add=True)),
                ('calificacion_promedio', models.FloatField(default=0.0)),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contenido.contenido')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('genero', models.CharField(blank=True, max_length=100)),
            ],
            bases=('contenido.contenido',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contenido.contenido')),
                ('temporadas', models.PositiveIntegerField(default=1)),
                ('episodios', models.PositiveIntegerField(default=1)),
                ('genero', models.CharField(blank=True, max_length=100)),
            ],
            bases=('contenido.contenido',),
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('contenido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contenido.contenido')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('tamaño_archivo', models.FloatField(help_text='Tamaño en GB')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
            },
            bases=('contenido.contenido',),
        ),
    ]
