# Generated by Django 5.1.6 on 2026-04-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_subidos', to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='contenido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadistica', to='contenido.contenido'),
        ),
    ]
