# Generated by Django 5.1.6 on 2026-04-13 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenidos'},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='contenido',
            old_name='calificacion_promedio',
            new_name='calificacionPromedio',
        ),
        migrations.RenameField(
            model_name='contenido',
            old_name='estado_aprobacion',
            new_name='estadoAprobacion',
        ),
        migrations.RenameField(
            model_name='estadistica',
            old_name='vistas',
            new_name='ventas',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='tamaño_archivo',
        ),
        migrations.AddField(
            model_name='contenido',
            name='fechaPublicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='contenido',
            name='genero',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='tamañoArchivo',
            field=models.FloatField(default=0.0, help_text='En GB'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(default=90, help_text='Duración en minutos'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='episodios',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
    ]
