# Generated by Django 5.1.6 on 2026-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_contenido_options_alter_pelicula_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo del contenido (video, .exe, .apk, etc.)', null=True, upload_to='contenidos/'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
