# Generated by Django 5.1.6 on 2026-04-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_contenido_archivo_contenido_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='episodios',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='temporadas',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
