# Generated by Django 5.1.6 on 2026-04-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_pelicula_duracion_alter_serie_episodios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo del contenido', max_length=255, null=True, upload_to='contenidos/'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='portada',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='portadas/'),
        ),
    ]
