# Generated by Django 5.1.6 on 2026-05-10 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_alter_contenido_archivo_alter_contenido_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='episodios',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='temporadas',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='archivo_pelicula',
            field=models.FileField(blank=True, help_text='Archivo de video de la película', null=True, upload_to='peliculas/'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='archivo_descarga',
            field=models.FileField(blank=True, help_text='Archivo para descargar', null=True, upload_to='juegos/descargas/'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='archivo_webgl',
            field=models.FileField(blank=True, help_text='Build WebGL para jugar en el navegador (index.html)', null=True, upload_to='juegos/webgl/'),
        ),
        migrations.CreateModel(
            name='RegistroDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Notas del parche v0.11.15', max_length=255)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_desarrollo', to='contenido.videojuego')),
            ],
            options={
                'verbose_name': 'Registro de Desarrollo',
                'verbose_name_plural': 'Registros de Desarrollo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('esta_cerrada', models.BooleanField(default=False)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='contenido.serie')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='episodios/')),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='contenido.temporada')),
            ],
            options={
                'ordering': ['temporada__numero', 'numero'],
                'unique_together': {('temporada', 'numero')},
            },
        ),
    ]
