# Generated by Django 5.1.6 on 2026-05-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_remove_contenido_archivo_remove_serie_episodios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='archivo_webgl',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='build_webgl',
            field=models.FileField(blank=True, help_text='Carpeta Build WebGL (index.html + archivos)', null=True, upload_to='juegos/webgl/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='archivo_descarga',
            field=models.FileField(blank=True, help_text='Archivo ZIP o ejecutable del juego para descargar', null=True, upload_to='juegos/descargas/'),
        ),
    ]
