# Generated by Django 5.1.6 on 2026-05-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_remove_videojuego_archivo_webgl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='episodio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Duración en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='archivo_pelicula',
            field=models.FileField(blank=True, null=True, upload_to='peliculas/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Duración en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tamañoArchivo',
            field=models.FloatField(default=0.0, editable=False, help_text='En GB'),
        ),
    ]
