# Generated by Django 5.1.6 on 2026-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_alter_episodio_options_alter_pelicula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='archivo',
            field=models.FileField(upload_to='episodios/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='archivo_descarga',
            field=models.FileField(blank=True, help_text='Archivo ZIP para descargar (opcional)', null=True, upload_to='juegos/descargas/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='build_webgl',
            field=models.FileField(blank=True, help_text='ZIP con el build WebGL (debe contener index.html)', null=True, upload_to='juegos/webgl/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tamañoArchivo',
            field=models.FloatField(default=0.0),
        ),
    ]
