# Generated by Django 5.1.6 on 2026-05-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0010_alter_episodio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='genero',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Género'),
        ),
    ]
