# Generated by Django 5.1.6 on 2026-05-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_alter_contenido_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['-fechaPublicacion'], 'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenidos'},
        ),
    ]
