# Generated by Django 5.1.6 on 2026-05-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_alter_contenido_options'),
        ('usuarios', '0003_alter_administrador_nivel_acceso_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['estadoAprobacion', '-fechaPublicacion'], name='contenido_c_estadoA_59ed3f_idx'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['genero'], name='contenido_c_genero_6d7f6e_idx'),
        ),
    ]
