# Generated by Django 5.1.6 on 2026-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default_avatar.png', null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo'), ('baneado', 'Baneado')], default='activo', max_length=20),
        ),
    ]
