# Generated by Django 5.1.6 on 2026-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_perfil_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='nivel_acceso',
            field=models.IntegerField(default=1, verbose_name='Nivel de acceso'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='es_desarrollador',
            field=models.BooleanField(default=False, verbose_name='Es desarrollador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre_desarrollador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre como desarrollador'),
        ),
        migrations.AlterField(
            model_name='moderador',
            name='nivel_permiso',
            field=models.IntegerField(default=1, verbose_name='Nivel de permiso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo'), ('baneado', 'Baneado')], default='activo', max_length=20, verbose_name='Estado de la cuenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre completo'),
        ),
    ]
