# Generated by Django 5.1.6 on 2026-04-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0002_initial'),
        ('social', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='contenido.contenido'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='usuarios.jugador'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('jugador', 'contenido')},
        ),
    ]
