# Generated by Django 5.1.6 on 2026-04-13 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_contenido_options_alter_pelicula_options_and_more'),
        ('social', '0002_initial'),
        ('usuarios', '0002_usuario_foto_perfil_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='contenido_texto',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='texto',
            new_name='contenido',
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='contenido.contenido'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('contenido', 'jugador')},
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenidos', models.ManyToManyField(blank=True, related_name='bibliotecas', to='contenido.contenido')),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to='usuarios.jugador')),
            ],
        ),
    ]
