# Generated by Django 5.1.6 on 2026-05-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_texto_comentario_contenido_texto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha']},
        ),
    ]
