# Generated by Django 5.1.6 on 2026-04-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('contenido', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='jugador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='compra',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='contenido.contenido'),
        ),
        migrations.AddField(
            model_name='compra',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='usuarios.jugador'),
        ),
        migrations.AddField(
            model_name='pago',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='compras.compra'),
        ),
    ]
