# Generated by Django 5.1.6 on 2026-04-13 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('contenido', '0003_alter_contenido_options_alter_pelicula_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='metodo_pago',
            new_name='metodoPago',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='videojuego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.videojuego'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fechaPago',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
    ]
